version: "3.7"
services:
  notebook:
    build: .
    command: ["jupyter", "lab"]
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/
    networks:
      - default

networks:
  default:
